# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 21:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dispPoc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='data',
            new_name='head',
        ),
        migrations.AddField(
            model_name='text',
            name='body',
            field=models.TextField(default=datetime.datetime(2016, 7, 7, 21, 49, 41, 382500, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
