# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispPoc', '0002_auto_20160707_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('data', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
