# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispPoc', '0003_auto_20160707_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('head', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='body',
        ),
        migrations.DeleteModel(
            name='head',
        ),
    ]
