# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispPoc', '0004_auto_20160707_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='body',
            field=models.TextField(help_text='latex body block'),
        ),
        migrations.AlterField(
            model_name='text',
            name='head',
            field=models.TextField(help_text='latex head block'),
        ),
    ]
