# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispPoc', '0006_auto_20160708_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='head',
            field=models.TextField(null=True),
        ),
    ]
