# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispPoc', '0007_auto_20160708_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='head',
            field=models.TextField(default='\n\\documentclass{report}\n\\usepackage{geometry}\n\\usepackage[dvipsnames]{xcolor}\n\\usepackage{hyperref}\n\\usepackage{graphicx}\n\\usepackage{float}\n\\usepackage{amsmath}\n\\usepackage{subcaption}\n\\usepackage{caption}\n\\usepackage{mathtools}\n\\usepackage{listings}\n\n\\graphicspath{ {images/}}\n\\hypersetup{\ncolorlinks=true,\nlinktoc=all,\nlinkcolor=blue!60,\n}\n\\geometry{legalpaper, portrait, margin=0.5in}\n\\lstdefinestyle{custom}{\n  basicstyle=\\small\\ttfamily,\n  columns=flexible,\n  breaklines=true,\n  frame=single,\n  language=Python ,\n  keepspaces=true,\n  backgroundcolor=\\color{gray!20},\n  keywordstyle=\\bfseries\\color{purple!70!black},\n  identifierstyle=\\color{black},\n  stringstyle=\\color{orange},\n  commentstyle=\\color{green!40!black}\n}\n\n\\lstset{style=custom}\n\n\\title{Default Title}\n\\author{Matt McNichols}\n\\date{\\today}\n\n\\DeclarePairedDelimiter\\floor{\\lfloor}{\\rfloor}\n'),
        ),
    ]
